export { BenefitsSection } from './benefits/BenefitsSection'
export { BrandsSection } from './brands/BrandsSection'
export { CoursesSection } from './courses/CoursesSection'
export { FaqSection } from './faq/FaqSection'
export { HeroSection } from './hero/HeroSection'
export { VideoSection } from './VideoSection'
